apiVersion: v1
kind: Service
metadata:
  name: dev-frontend-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: dev-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
